### ISSUE TITLE
Running the simulation

### ISSUE THREAD

**Issue by cmalerdos** [AMZ-Driverless/fssim#6]
Hello,

In the section "How to run it in your workspace" in the last step you write "you can start controlling the vehicle with /fssim/cmd topic". How do I use this topic with ROS? What do I have to do?

Thank you in advance.

**Comment by kabzo** [comment]
Hi @cmalerdos , you can use `rostopic pub -r 100 /fssim/cmd ...`. But I strongly suggest you start with the `fsd_skeleton` because that gives you a full solution. And then look into to controller code in fsd_skeleton, which can give you a clear idea how to control the vehicle: https://github.com/AMZ-Driverless/fsd_skeleton/blob/master/src/3_control/control_pure_pursuit/src/pure_pursuit.cpp#L65
